'use strict';
const $=id=>document.getElementById(id),app=$('app'),isHost=new URLSearchParams(location.search).get('role')==='host',isJoin=!isHost;
document.body.classList.toggle('host',isHost);
const requestedCourse=new URLSearchParams(location.search).get('course');
const course=['binary','logic'].includes(requestedCourse)?requestedCourse:'';
const courseTitle=()=>state?.title||(course==='binary'?'2進数バトル':course==='logic'?'論理回路バトル':'クイズバトル');
const courseCount=()=>state?.total||(course==='binary'?6:5);
function showCourseTitle(){document.title=courseTitle()+'｜情報Ⅰ';document.querySelector('.brand span').textContent=courseTitle();}

const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let info,session,state,stream,selectedAvatar='🐶',offset=0,lastView='',connected=false,base=Innovia.root.href.replace(/\/$/,'');
const key=(isHost?'innovia-battle-host':'innovia-battle-player')+(course?'-'+course:'');let stored;try{stored=JSON.parse(sessionStorage.getItem(key))}catch{}
function notice(t){$('notice').textContent=t;clearTimeout(notice.timer);notice.timer=setTimeout(()=>$('notice').textContent='',7000)}
async function api(route,data){await Innovia.ready(isHost?'teacher':'student');return Innovia.rpc('innovia_battle',{p_action:route,p_payload:data||{}},isHost?'teacher':'student');}
function save(s){session=s;sessionStorage.setItem(key,JSON.stringify(s));if(s.room)Innovia.subscribe(s.room,isHost?'teacher':'student',()=>poll()).catch(()=>{});connect()}
const audio={ctx:null,enabled:false,volume:.5,mode:'game',beat:0,interval:null,awardNodes:new Set(),awardBus:null,awardCompressor:null,awardTimer:null,
 async enable(){
  if(!this.ctx||this.ctx.state==='closed'){
   const AudioEngine=window.AudioContext||window.webkitAudioContext;
   if(!AudioEngine)throw Error('このブラウザは音声再生に対応していません。');
   this.ctx=new AudioEngine();this.ctx.onstatechange=()=>syncSound();
  }
  // Called directly by a tap/click so iPad and Chromebook can unlock audio.
  let timeout;try{await Promise.race([this.ctx.resume(),new Promise((_,reject)=>{timeout=setTimeout(()=>reject(Error('音声を再開できません。もう一度「音を開始・試聴」を押してください。')),2000)})]);}finally{clearTimeout(timeout)}
  if(this.ctx.state!=='running')throw Error('音声が一時停止しています。もう一度押してください。');
  this.enabled=true;if(!this.interval)this.interval=setInterval(()=>this.tick(),210);syncSound();
 },
 stop(){this.enabled=false;this.cancelAward();clearInterval(this.interval);this.interval=null;this.ctx?.suspend().catch(()=>{});syncSound()},
 setVolume(value){this.volume=Number(value);if(this.awardBus)this.awardBus.gain.setTargetAtTime(this.volume*.7,this.ctx.currentTime,.02);syncSound()},
 cancelAward(){clearTimeout(this.awardTimer);this.awardTimer=null;for(const node of this.awardNodes){try{node.stop()}catch{}node.disconnect()}this.awardNodes.clear();this.awardBus?.disconnect();this.awardCompressor?.disconnect();this.awardBus=null;this.awardCompressor=null},
 note(freq,duration=.15,type='sine',amp=1,delay=0,bus=null){if(!this.enabled||this.ctx?.state!=='running'||this.volume===0)return;const t=this.ctx.currentTime+delay,o=this.ctx.createOscillator(),g=this.ctx.createGain();o.type=type;o.frequency.value=freq;g.gain.setValueAtTime(0,t);g.gain.linearRampToValueAtTime((bus?1:this.volume)*.4*amp,t+.01);g.gain.exponentialRampToValueAtTime(.001,t+duration);o.connect(g);g.connect(bus||this.ctx.destination);if(bus)this.awardNodes.add(o);o.onended=()=>{this.awardNodes.delete(o);o.disconnect();g.disconnect()};o.start(t);o.stop(t+duration+.03)},
 clap(delay,amp,bus){const ctx=this.ctx,duration=.12,buffer=ctx.createBuffer(1,Math.ceil(ctx.sampleRate*duration),ctx.sampleRate),samples=buffer.getChannelData(0);for(let i=0;i<samples.length;i++)samples[i]=(Math.random()*2-1)*Math.exp(-i/(ctx.sampleRate*.025));const source=ctx.createBufferSource(),filter=ctx.createBiquadFilter(),gain=ctx.createGain();source.buffer=buffer;filter.type='bandpass';filter.frequency.value=1300+Math.random()*700;filter.Q.value=.65;gain.gain.value=amp;source.connect(filter);filter.connect(gain);gain.connect(bus);this.awardNodes.add(source);source.onended=()=>{this.awardNodes.delete(source);source.disconnect();filter.disconnect();gain.disconnect()};source.start(ctx.currentTime+delay)},
 award(){
  if(!this.enabled||this.ctx?.state!=='running'||this.volume===0)return false;
  this.cancelAward();const bus=this.ctx.createGain(),compressor=this.ctx.createDynamicsCompressor();bus.gain.value=this.volume*.7;compressor.threshold.value=-16;compressor.knee.value=12;compressor.ratio.value=4;compressor.attack.value=.003;compressor.release.value=.18;bus.connect(compressor);compressor.connect(this.ctx.destination);this.awardBus=bus;this.awardCompressor=compressor;
  // Original victory theme: bright brass-like chords, rising melody, and synthesized applause.
  const chords=[[261.63,329.63,392],[293.66,392,493.88],[261.63,349.23,440],[293.66,392,493.88],[261.63,329.63,392,523.25]];
  chords.forEach((chord,i)=>{const at=i*.72;chord.forEach(f=>{this.note(f,i===4?1.65:.5,'triangle',.28,at,bus);this.note(f*2,i===4?1.6:.45,'sawtooth',.055,at,bus)});this.note(i===2?87.31:i===1||i===3?98:130.81,.55,'sine',.6,at,bus)});
  [[523.25,0],[523.25,.18],[659.25,.36],[783.99,.72],[659.25,1.08],[698.46,1.44],[880,1.8],[783.99,2.16],[987.77,2.52],[1046.5,2.88]].forEach(([f,at],i)=>this.note(f,i===9?1.65:.23,'triangle',.6,at,bus));
  for(let i=0;i<70;i++){const at=2.8+i*.045+Math.random()*.06;this.clap(at,.26*(1-i/100),bus)}
  this.awardTimer=setTimeout(()=>this.cancelAward(),6600);return true;
 },
 tick(){if(!isHost||!state||!this.enabled||this.mode==='none')return;const n=this.beat++;if(state.phase==='finished')return;const tune=this.mode==='game'?[262,330,392,523,392,330,440,392]:this.mode==='electro'?[147,147,294,220,175,175,349,262]:[131,0,196,0,165,0,196,0];const f=tune[n%8];if(f)this.note(f,this.mode==='calm'?.36:.12,this.mode==='electro'?'triangle':'sine',state.phase==='question'?.7:.4);if(n%4===0)this.note(65,.11,'triangle',.5)},
 effect(kind){const seq=kind==='correct'?[523,659,784]:kind==='wrong'?[220,147]:kind==='rank'?[392,523,659,784]:[740];seq.forEach((f,i)=>this.note(f,.18,'sine',1.8,i*.12))}
};
let pollTimer, polling=false;
async function poll(){if(polling||!session)return;polling=true;try{const next=await api('state',session),old=state;connected=true;$('connection').textContent='● 接続中';state=next;offset=state.serverNow-Date.now();audio.mode=state.bgm;if(old&&old.phase!==state.phase){if(state.phase==='reveal')audio.effect(isHost?'rank':state.me?.answer?.correct?'correct':'wrong');if(state.phase==='finished'){if(isHost)audio.award();else audio.effect('rank')}}render();document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=isHost||state.phase!=='question'||!!state.me?.answer||Date.now()+offset>=state.deadline);}catch(e){connected=false;$('connection').textContent='再接続中';document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=true);notice(e.message);}finally{polling=false;clearTimeout(pollTimer);pollTimer=setTimeout(poll,1000)}}
function connect(){clearTimeout(pollTimer);lastView='';poll()}
function soundControls(){return `<div class="sound"><button id="audio" class="small">音を開始・試聴</button><button id="audio-stop" class="small">音を停止</button>${isHost&&state?.phase==='finished'?'<button id="award-replay" class="small">表彰音をもう一度</button>':''}${isHost&&state?`<label for="bgm">BGM</label><select id="bgm"><option value="game">ゲームショー</option><option value="electro">電子音</option><option value="calm">落ち着いたビート</option><option value="none">BGMなし</option></select>`:''}<label for="volume">音量</label><input id="volume" type="range" min="0" max="1" step="0.01" value="${audio.volume}" aria-label="音量"><span id="audio-status" role="status"></span></div><p class="sound-help">最初に「音を開始・試聴」を押してください。${isHost?'BGMは先生の端末から流れます。表彰ではファンファーレと拍手の音が鳴ります。':'生徒の端末は結果発表の効果音だけ鳴ります。待機中のBGMはありません。'} 聞こえないときは端末・タブのミュートと、スピーカー／HDMIの出力先を確認してください。</p>`}
function syncSound(){if(!$('audio-status'))return;const playing=audio.enabled&&audio.ctx?.state==='running';$('audio').textContent=playing?'もう一度試聴':audio.enabled?'音を再開・試聴':'音を開始・試聴';$('audio-stop').disabled=!audio.enabled;if($('award-replay'))$('award-replay').disabled=!playing||audio.volume===0;$('audio-status').textContent=audio.volume===0?'音量0（無音）':playing?'音声再生中':audio.enabled?'一時停止中：再開を押してください':'音声未開始';}
function bindSound(){syncSound();$('audio').onclick=async()=>{const button=$('audio');button.disabled=true;try{await audio.enable();if(isHost&&state?.phase==='finished')audio.award();else audio.effect('rank')}catch(e){notice(e.message||'音を開始できません。端末の音量設定を確認してください。')}finally{button.disabled=false;syncSound()}};$('audio-stop').onclick=()=>audio.stop();$('volume').oninput=e=>audio.setVolume(e.target.value);if($('award-replay'))$('award-replay').onclick=()=>audio.award();if($('bgm')){$('bgm').value=state.bgm;$('bgm').onchange=e=>control('bgm',{bgm:e.target.value})}}
function rows(players,limit=100){return players.slice(0,limit).map(p=>`<div class="rankrow ${p.id===state.me?.id?'mine':''}"><b>${p.rank}</b><span class="face">${esc(p.avatar)}</span><span>${esc(p.name)}</span><b>${p.score.toLocaleString()} <small>pt</small></b></div>`).join('')}
function circuit(reveal){return `<svg class="circuit ${reveal?'revealed':''}" role="img" aria-label="A=1とB=0をANDに入力してP。BをNOTに入力してQ。PとQをORに入力してY、ANDに入力してZ。" viewBox="0 0 820 245"><text x="10" y="43">A = 1</text><text x="10" y="133">B = 0</text><path d="M80 36H160V56H210 M80 125H130V84H210 M130 125V182H210 M310 70H390V56H505 M310 182H430V85H505 M390 70V168H505 M430 182V196H505 M605 70H700 M605 182H700"/><circle cx="130" cy="125" r="6" fill="#fff"/><circle cx="390" cy="70" r="6" fill="#fff"/><circle cx="430" cy="182" r="6" fill="#fff"/><rect x="210" y="44" width="100" height="52" rx="12"/><rect x="210" y="156" width="100" height="52" rx="12"/><rect x="505" y="44" width="100" height="52" rx="12"/><rect x="505" y="156" width="100" height="52" rx="12"/><text x="238" y="78">AND</text><text x="238" y="190">NOT</text><text x="535" y="78">OR</text><text x="530" y="190">AND</text><text x="330" y="49" class="signal">P${reveal?'='+esc(state.reveal?.signals?.p??'?'):''}</text><text x="330" y="225" class="signal">Q${reveal?'='+esc(state.reveal?.signals?.q??'?'):''}</text><text x="705" y="78" class="signal">Y = ${reveal?esc(state.reveal?.signals?.y??'?'):'?'}</text><text x="705" y="190" class="signal">Z = ${reveal?esc(state.reveal?.signals?.z??'?'):'?'}</text></svg>`}
function render(){
 showCourseTitle();
 document.body.classList.toggle('ranking-screen',isHost&&state.phase==='reveal');
 const view=[state.phase,state.index,state.me?.answer?.choice??'',state.bgm].join(':');
 if(view===lastView){if($('people'))$('people').innerHTML=people();if($('number'))$('number').textContent=state.players.length;if($('answered'))$('answered').textContent=`${state.answered} / ${state.players.length} 人が回答`;if($('start'))$('start').disabled=!state.players.length;return}lastView=view;
 if(state.phase==='lobby'){
 if(isHost)app.innerHTML=`${soundControls()}<div class="grid"><section class="panel"><div class="eyebrow">${esc(courseTitle())}</div><h1>準備はいい？<br>みんなで挑戦しよう。</h1><div class="row"><div id="qr" class="qr"></div><div><div class="muted">参加PIN</div><div class="pin">${state.pin}</div></div></div><p>QRを読み取るか、参加URLを開いてPINを入力。</p><div id="joinurl" class="url"></div><label for="network">参加サイトのアドレス</label><select id="network">${[...new Set([base,...info.urls])].map(v=>`<option value="${esc(v)}">${esc(v)}</option>`).join('')}</select><p style="font-size:14px">INNOVIAの「${esc(courseTitle())}」からPINを入力しても参加できます。</p></section><section class="panel"><div class="row between"><h2>エントリー</h2><span><b id="number" class="count">${state.players.length}</b> 人</span></div><div id="people" class="people">${people()}</div><p>${esc(courseTitle())} · 全${state.total}問<br>正解10点 ＋ 速さで0〜10点（最大20点）<br>不正解・未回答は0点</p><button id="start" ${!state.players.length?'disabled':''}>バトルを開始 ▶</button><p>全員が参加したら開始。開始後の新規参加はできません。全員回答または時間切れで自動的に正解を発表します。次の問題へは先生が進めます。</p></section></div>`;
 else{const me=state.players.find(p=>p.id===state.me.id);app.innerHTML=`${soundControls()}<section class="waiting panel"><div class="eyebrow">${esc(courseTitle())} · 全${state.total}問</div><div class="face">${esc(me.avatar)}</div><h1>${esc(me.name)}</h1><h2>参加できました！</h2><p>先生がスタートするまで待ってね。<br>この画面を開いたままにしておこう。</p><span class="badge">ROOM ${state.pin}</span></section>`}
 bindSound();if(isHost){$('network').value=base;$('network').onchange=e=>{base=e.target.value;drawQR()};drawQR();$('start').onclick=()=>control('start')}return;
 }
 if(state.phase==='finished'){
 const top=state.players.slice(0,3);app.innerHTML=`${soundControls()}<div class="question"><div class="eyebrow">${esc(courseTitle())} · 結果発表</div><h1>最後まで、ナイスチャレンジ！</h1><p>同じ点数は同順位です。</p><div class="podium">${[top[1],top[0],top[2]].filter(Boolean).map(p=>`<div class="pod ${p.rank===1?'first':''}"><div class="face">${esc(p.avatar)}</div><h2>${p.rank===1?'🥇':p.rank===2?'🥈':'🥉'} ${p.rank}位</h2><h2>${esc(p.name)}</h2><b>${p.score.toLocaleString()} pt</b></div>`).join('')}</div></div><section class="panel"><h2>最終ランキング</h2>${rows(state.players)}</section>${isHost?'<p>もう一度遊ぶときは先生画面を新しいタブで開き、新しいルームを作成してください。</p>':''}`;bindSound();return;
 }
 const q=state.question,revealed=state.phase==='reveal',answered=!!state.me?.answer;
 if(isHost&&revealed){
  const count=Math.max(1,state.players.length);
  app.innerHTML=`<section class="ranking-stage" aria-labelledby="ranking-heading"><div class="ranking-heading"><h1 id="ranking-heading">🏆 ランキング</h1><span>${state.index+1} / ${state.total} 問</span></div><div class="ranking-list" style="--rank-rows-one:${count};--rank-rows-two:${Math.ceil(count/2)};--rank-rows-three:${Math.ceil(count/3)};--rank-columns-two:${count>6?2:1};--rank-rows-medium:${count>6?Math.ceil(count/2):count};--rank-columns-wide:${count>20?3:count>6?2:1};--rank-rows-wide:${count>20?Math.ceil(count/3):count>6?Math.ceil(count/2):count}">${rows(state.players)}</div><div class="ranking-actions"><button id="advance">${state.index===state.total-1?'表彰台を発表 🏆':'次の問題へ ▶'}</button></div></section>`;
  $('advance').onclick=()=>control('next');
  window.scrollTo({top:0,left:0,behavior:'auto'});
  return;
 }
 app.innerHTML=`${soundControls()}<section class="question"><div class="questionbar"><span class="eyebrow">${esc(q.stage)}</span><span>${state.index+1} / ${state.total}</span><span class="timer" id="timer">—</span></div><div class="progress"><div id="bar"></div></div><h1>${esc(q.title)}</h1>${q.boss?circuit(revealed):''}<div class="answers">${q.choices.map((c,i)=>`<button data-choice="${i}" class="answer ${state.me?.answer?.choice===i?'selected':''} ${revealed?(state.reveal.correct===i?'correct':'dim'):''}" ${(isHost||revealed||answered||!connected)?'disabled':''}><strong>${['▲','◆','●','■'][i]}</strong><span>${esc(c)}</span>${revealed?`<small> · ${state.reveal.counts[i]}人</small>`:''}</button>`).join('')}</div><div class="feedback">${revealed?`${!isHost?(state.me?.answer?.correct?`正解！ +${state.me.answer.points}点`:'次の問題でチャレンジ！'):'正解：'+esc(q.choices[state.reveal.correct])}`:answered?'回答を受け付けました。結果を待ってね。':isHost?'全員回答または時間切れで、自動的に正解を発表します':'答えを1つ選ぼう！'}</div>${revealed?`<div class="panel"><h2>解説</h2><p>${esc(state.reveal.explain)}</p></div>`:''}<p id="answered">${state.answered} / ${state.players.length} 人が回答</p>${isHost?`<button id="advance">${revealed?(state.index===state.total-1?'表彰台を発表 🏆':'次の問題へ ▶'):'締め切って正解を発表'}</button>`:''}</section>${revealed?`<section class="ranking"><h2>🏆 ${isHost?'現在のランキング':'ランキング'}</h2>${rows(state.players,isHost?10:100)}${isHost&&state.players.length>10?'<p>上位10人を表示しています。</p>':''}</section>`:''}`;
 bindSound();if(isHost)$('advance').onclick=()=>control(revealed?'next':'reveal');else document.querySelectorAll('[data-choice]').forEach(btn=>btn.onclick=async()=>{document.querySelectorAll('[data-choice]').forEach(x=>x.disabled=true);try{await api('answer',{...session,index:state.index,choice:Number(btn.dataset.choice)});await poll()}catch(e){notice(e.message);lastView='';render()}});updateTimer();
}
function people(){return state.players.length?state.players.map(p=>`<div class="person"><span>${esc(p.avatar)}</span>${esc(p.name)}${p.online?'':' · 接続待ち'}</div>`).join(''):'<p>最初のチャレンジャーを待っています…</p>'}
function drawQR(){const url=base+'/battle/?course='+encodeURIComponent(state.course)+'&pin='+state.pin;$('joinurl').textContent=url;try{const qr=qrcode(0,'M');qr.addData(url);qr.make();$('qr').innerHTML=qr.createSvgTag({cellSize:4,margin:16,scalable:true});$('qr').setAttribute('aria-label','参加用QRコード')}catch{$('qr').textContent='QRを表示できません。参加URLを入力してください。'}}
async function control(action,extra={}){try{await api('control',{...session,action,index:state.index,...extra});await poll()}catch(e){notice(e.message)}}
let lastSecond=-1;function updateTimer(){if(!$('timer'))return;const left=Math.max(0,Math.ceil((state.deadline-Date.now()-offset)/1000));$('timer').textContent=state.phase==='reveal'?'解説':left+'秒';$('bar').style.width=(state.phase==='reveal'?0:Math.min(100,left/state.question.seconds*100))+'%';if(state.phase==='question'&&left<=5&&left>0&&left!==lastSecond&&isHost)audio.effect('tick');lastSecond=left;if(left===0)document.querySelectorAll('[data-choice]').forEach(b=>b.disabled=true)}setInterval(updateTimer,200);
async function init(){info={avatars:Innovia.avatars,local:false,urls:[]};if(isHost&&Innovia.configured()){const settings=await Innovia.rpc('innovia_settings',{},'teacher');info.local=settings.teacher;}$('connection').textContent='準備OK';showCourseTitle();
 if(!course&&!new URLSearchParams(location.search).get('pin')){
  const route=Innovia.root.href+(isHost?'battle/host/':'battle/');
  app.innerHTML=`<section class="hero"><h1>教材を選ぼう</h1><div class="grid"><a class="panel link" target="_top" href="${route}?course=binary"><h2>2進数バトル</h2><p>加算・減算の6問</p></a><a class="panel link" target="_top" href="${route}?course=logic"><h2>論理回路バトル</h2><p>AND・OR・NOTと回路の5問</p></a></div></section>`;return;
 }
 if(isHost){base=Innovia.root.href.replace(/\/$/,'');app.innerHTML=`${soundControls()}<section class="hero"><div class="eyebrow">先生用ホスト</div><h1>${esc(courseTitle())}</h1><p>全${courseCount()}問のクイズバトル。正解10点＋速さで最大10点。<br>ルームを作成し、この画面をプロジェクターに映してください。</p><div class="row"><button id="create" ${!info.local?'disabled':''}>ルームを作成 ⚡</button>${stored?'<button id="resume" class="small">前のルームに戻る</button>':''}</div>${!info.local?'<p><a href="'+Innovia.root.href+'teacher/">先生用ページでログインしてください。</a></p>':''}</section>`;$('create').onclick=async()=>{try{save(await api('create',{course}))}catch(e){notice(e.message)}};if($('resume'))$('resume').onclick=()=>save(stored);
 }else if(isJoin){const pin=new URLSearchParams(location.search).get('pin')||'';app.innerHTML=`${soundControls()}<form class="panel" id="entry"><div class="eyebrow">アバターを選んで参加</div><h1>${esc(courseTitle())}</h1><p>全${courseCount()}問 · 正解10点＋速さで最大10点</p><label for="pin">6桁の参加PIN</label><input id="pin" inputmode="numeric" pattern="[0-9]{6}" maxlength="6" value="${esc(pin)}" required autocomplete="off"><label for="name">ニックネーム（本名・学籍番号は使わない）</label><input id="name" maxlength="12" placeholder="例：ねこパンチ" required autocomplete="off"><label>アバターを選ぼう</label><div class="avatars">${info.avatars.map((a,i)=>`<button type="button" class="avatar ${i===0?'selected':''}" aria-label="アバター ${esc(a)}" aria-pressed="${i===0}" data-avatar="${esc(a)}">${a}</button>`).join('')}</div><button type="submit" id="join">参加する ▶</button>${stored?'<button type="button" id="resume" class="small">参加済みのルームに戻る</button>':''}<p>ルームは8時間で利用期限が切れます。<br>架空のニックネームと得点をサイトに保存します。本名は使わないでください。</p></form>`;document.querySelectorAll('[data-avatar]').forEach(btn=>btn.onclick=()=>{selectedAvatar=btn.dataset.avatar;document.querySelectorAll('[data-avatar]').forEach(b=>{b.classList.toggle('selected',b===btn);b.setAttribute('aria-pressed',String(b===btn))})});$('entry').onsubmit=async e=>{e.preventDefault();$('join').disabled=true;try{save(await api('join',{course:course||undefined,pin:$('pin').value,name:$('name').value,avatar:selectedAvatar,token:stored?.pin===$('pin').value?stored.token:undefined}))}catch(err){notice(err.message);$('join').disabled=false}};if($('resume'))$('resume').onclick=()=>save(stored);
 }else app.innerHTML='<section class="hero"><div class="eyebrow">INFORMATION I · QUIZ ARENA</div><h1>LOGIC<br><em>AMIDA BATTLE</em></h1><p>2進数のその先へ。みんなで挑む、論理回路バトル。</p><div class="row"><a class="link panel" href="/join">生徒：バトルに参加 →</a><a class="link panel" href="/host">先生：ルームを作成 →</a></div></section>';}
$('fullscreen').onclick=()=>{if(document.fullscreenElement)document.exitFullscreen();else document.documentElement.requestFullscreen?.().catch(()=>notice('ブラウザの全画面機能をご利用ください。'))};init().then(()=>{if($('audio'))bindSound()}).catch(e=>notice(e.message||'接続できません。設定とインターネット接続を確認してください。'));
if(document.modelContext?.registerTool){const lifecycle=new AbortController();window.addEventListener('pagehide',()=>lifecycle.abort(),{once:true});try{Promise.resolve(document.modelContext.registerTool({name:'read_quiz_status',title:'クイズの進行状況',description:'現在の画面の進行段階、問題番号、参加人数、回答人数を読み取ります。',inputSchema:{type:'object',properties:{},additionalProperties:false},annotations:{readOnlyHint:true},execute(input){if(!input||Object.keys(input).length)throw Error('入力項目はありません。');return state?{phase:state.phase,question:state.index+1,total:state.total,participants:state.players.length,answered:state.answered}:{phase:'entry'};}},{signal:lifecycle.signal})).catch(()=>{})}catch{}}
